export { CovidInfoBox } from './CovidInfoBox';
export { CountrySelect } from './CountrySelect';
export { CovidInfoSection } from './CovidInfoSection';

export const flags = {
  'Afghanistan': '🇦🇫', 'Aland Islands': '🇦🇽', 'Albania': '🇦🇱', 'Algeria': '🇩🇿', 'American Samoa': '🇦🇸', 'Andorra': '🇦🇩',
  'Angola': '🇦🇴', 'Anguilla': '🇦🇮', 'Antarctica': '🇦🇶', 'Antigua and Barbuda': '🇦🇬', 'Argentina': '🇦🇷', 'Armenia': '🇦🇲', 'Aruba': '🇦🇼',
  'Australia': '🇦🇺', 'Austria': '🇦🇹', 'Azerbaijan': '🇦🇿', 'Bahamas': '🇧🇸', 'Bahrain': '🇧🇭', 'Bangladesh': '🇧🇩', 'Barbados': '🇧🇧',
  'Belarus': '🇧🇾', 'Belgium': '🇧🇪', 'Belize': '🇧🇿', 'Benin': '🇧🇯', 'Bermuda': '🇧🇲', 'Bhutan': '🇧🇹', 'Bolivia': '🇧🇴',
  'Bonaire, Saint Eustatius and Saba': '🇳🇱', 'Bosnia and Herzegovina': '🇧🇦', 'Botswana': '🇧🇼', 'Bouvet Island': '🇧🇻', 'Brazil': '🇧🇷',
  'British Indian Ocean Territory': '🇮🇴', 'British Virgin Islands': '🇻🇬', 'Brunei': '🇧🇳', 'Bulgaria': '🇧🇬', 'Burkina Faso': '🇧🇫', 'Burundi': '🇧🇮',
  'Cambodia': '🇰🇭', 'Cameroon': '🇨🇲', 'Canada': '🇨🇦', 'Cape Verde': '🇨🇻', 'Cayman Islands': '🇰🇾', 'Central African Republic': '🇨🇫', 'Chad': '🇹🇩',
  'Chile': '🇨🇱', 'Mainland China': '🇨🇳', 'Christmas Island': '🇨🇽', 'Cocos Islands': '🇨🇨', 'Colombia': '🇨🇴', 'Comoros': '🇰🇲', 'Cook Islands': '🇨🇰',
  'Costa Rica': '🇨🇷', 'Croatia': '🇭🇷', 'Cuba': '🇨🇺', 'Curacao': '🇨🇼', 'Cyprus': '🇨🇾', 'Czechia': '🇨🇿', 'Democratic Republic of the Congo': '🇨🇩',
  'Denmark': '🇩🇰', 'Djibouti': '🇩🇯', 'Dominica': '🇩🇲', 'Dominican Republic': '🇩🇴', 'East Timor': '🇹🇱', 'Ecuador': '🇪🇨', 'Egypt': '🇪🇬',
  'El Salvador': '🇸🇻', 'Equatorial Guinea': '🇬🇶', 'Eritrea': '🇪🇷', 'Estonia': '🇪🇪', 'Ethiopia': '🇪🇹', 'Falkland Islands': '🇫🇰',
  'Faroe Islands': '🇫🇴', 'Fiji': '🇫🇯', 'Finland': '🇫🇮', 'France': '🇫🇷', 'French Guiana': '🇬🇫', 'French Polynesia': '🇵🇫',
  'French Southern Territories': null, 'Gabon': '🇬🇦', 'Gambia, The': '🇬🇲', 'Georgia': '🇬🇪', 'Germany': '🇩🇪', 'Ghana': '🇬🇭', 'Gibraltar': '🇬🇮',
  'Greece': '🇬🇷', 'Greenland': '🇬🇱', 'Grenada': '🇬🇩', 'Guadeloupe': '🇬🇵', 'Guam': '🇬🇺', 'Guatemala': '🇬🇹', 'Guernsey': '🇬🇬',
  'Guinea-Bissau': '🇬🇼', 'Guinea': '🇬🇳', 'Guyana': '🇬🇾', 'Haiti': '🇭🇹', 'Heard Island and McDonald Islands': '🇭🇲',
  'Honduras': '🇭🇳', 'Hong Kong': '🇭🇰', 'Hungary': '🇭🇺', 'Iceland': '🇮🇸', 'India': '🇮🇳', 'Indonesia': '🇮🇩', 'Iran': '🇮🇷',
  'Iraq': '🇮🇶', 'Ireland': '🇮🇪', 'Isle of Man': '🇮🇲', 'Israel': '🇮🇱', 'Italy': '🇮🇹', 'Ivory Coast': '🇨🇮', 'Jamaica': '🇯🇲',
  'Japan': '🇯🇵', 'Jersey': '🇯🇪', 'Jordan': '🇯🇴', 'Kazakhstan': '🇰🇿', 'Kenya': '🇰🇪', 'Kiribati': '🇰🇮', 'Korea, South': '🇰🇷',
  'Kosovo': '🇽🇰', 'Kuwait': '🇰🇼', 'Kyrgyzstan': '🇰🇬', 'Laos': '🇱🇦', 'Latvia': '🇱🇻', 'Lebanon': '🇱🇧', 'Lesotho': '🇱🇸',
  'Liberia': '🇱🇷', 'Libya': '🇱🇾', 'Liechtenstein': '🇱🇮', 'Lithuania': '🇱🇹', 'Luxembourg': '🇱🇺', 'Macao': '🇲🇴', 'Macedonia': '🇲🇰',
  'Madagascar': '🇲🇬', 'Malawi': '🇲🇼', 'Malaysia': '🇲🇾', 'Maldives': '🇲🇻', 'Mali': '🇲🇱', 'Malta': '🇲🇹', 'Marshall Islands': '🇲🇭',
  'Martinique': '🇲🇶', 'Mauritania': '🇲🇷', 'Mauritius': '🇲🇺', 'Mayotte': '🇾🇹', 'Mexico': '🇲🇺', 'Micronesia': '🇫🇲', 'Moldova': '🇲🇩',
  'Monaco': '🇲🇨', 'Mongolia': '🇲🇳', 'Montenegro': '🇲🇪', 'Montserrat': '🇲🇸', 'Morocco': '🇲🇦', 'Mozambique': '🇲🇿', 'Myanmar': '🇲🇲',
  'Namibia': '🇳🇦', 'Nauru': '🇳🇷', 'Nepal': '🇳🇵', 'Netherlands': '🇳🇱', 'New Caledonia': '🇳🇨', 'New Zealand': '🇳🇿', 'Nicaragua': '🇳🇮',
  'Niger': '🇳🇪', 'Nigeria': '🇳🇬', 'Niue': '🇳🇺', 'Norfolk Island': '🇳🇫', 'Northern Mariana Islands': '🇲🇵', 'Norway': '🇳🇴', 'Oman': '🇴🇲',
  'Pakistan': '🇵🇰', 'Palau': '🇵🇼', 'Palestinian Territory': '🇵🇸', 'Panama': '🇵🇦', 'Papua New Guinea': '🇵🇬', 'Paraguay': '🇵🇾',
  'People\'s Republic of Korea': '🇰🇵', 'Peru': '🇵🇪', 'Philippines': '🇵🇭', 'Pitcairn': '🇵🇳', 'Poland': '🇵🇱', 'Portugal': '🇵🇹', 'Puerto Rico': '🇵🇷',
  'Qatar': '🇶🇦', 'Republic of the Congo': '🇨🇬', 'Reunion': '🇷🇪', 'Romania': '🇷🇴', 'Russia': '🇷🇺', 'Rwanda': '🇷🇼', 'Saint Barthelemy': '🇧🇱',
  'Saint Helena': '🇸🇭', 'Saint Kitts and Nevis': '🇰🇳', 'Saint Lucia': '🇱🇨', 'Saint Martin': '🇸🇽', 'Saint Pierre and Miquelon': '🇵🇲',
  'Saint Vincent and the Grenadines': '🇻🇨', 'Samoa': '🇼🇸', 'San Marino': '🇸🇲', 'Sao Tome and Principe': '🇸🇹', 'Saudi Arabia': '🇸🇦',
  'Senegal': '🇸🇳', 'Serbia': '🇷🇸', 'Seychelles': '🇸🇨', 'Sierra Leone': '🇸🇱', 'Singapore': '🇸🇬', 'Sint Maarten': '🇸🇽',
  'Slovakia': '🇸🇰', 'Slovenia': '🇸🇮', 'Solomon Islands': '🇸🇧', 'Somalia': '🇸🇴', 'South Africa': '🇿🇦', 'South Georgia and the South Sandwich Islands': '🇬🇸',
  'South Sudan': '🇸🇩', 'Spain': '🇪🇸', 'Sri Lanka': '🇱🇰', 'Sudan': '🇸🇩', 'Suriname': '🇸🇷', 'Svalbard and Jan Mayen': '🇸🇯',
  'Swaziland': '🇸🇿', 'Sweden': '🇸🇪', 'Switzerland': '🇨🇭', 'Syria': '🇸🇾', 'Taiwan*': '🇹🇼', 'Tajikistan': '🇹🇯', 'Tanzania': '🇹🇿',
  'Thailand': '🇹🇭', 'Togo': '🇹🇬', 'Tokelau': '🇹🇰', 'Tonga': '🇹🇴', 'Trinidad and Tobago': '🇹🇹', 'Tunisia': '🇹🇳', 'Turkey': '🇹🇷',
  'Turkmenistan': '🇹🇲', 'Turks and Caicos Islands': '🇹🇨', 'Tuvalu': '🇹🇻', 'U.S. Virgin Islands': '🇻🇮', 'Uganda': '🇺🇬', 'Ukraine': '🇺🇦',
  'United Arab Emirates': '🇦🇪', 'United Kingdom': '🇬🇧', 'United States Minor Outlying Islands': '🇺🇸', 'Uruguay': '🇺🇾', 'US': '🇺🇸',
  'Uzbekistan': '🇺🇿', 'Vanuatu': '🇻🇺', 'Vatican': '🇻🇦', 'Venezuela': '🇻🇪', 'Vietnam': '🇻🇳', 'Wallis and Futuna': '🇼🇫', 'Western Sahara': '🇪🇭',
  'Yemen': '🇾🇪', 'Zambia': '🇿🇲', 'Zimbabwe': '🇿🇼', };
